ALTER TABLE usuario
    MODIFY COLUMN sobrenome VARCHAR(100) NULL,
    MODIFY COLUMN cidade VARCHAR(100) NULL,
    MODIFY COLUMN bairro VARCHAR(100) NULL,
    MODIFY COLUMN numero VARCHAR(12) NULL,
    MODIFY COLUMN telefone VARCHAR(15) NULL;